################################# Default configuration ###################
baseURL = "/"
title = "Myanmar Enterprise Solutions"
theme = "mesc"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
# disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []
 
############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

############################# Navigation ##################################
[[menu.main]]
name = "about"
pre = ""
url = "/about"
weight = 1

[[menu.main]]
name = "services"
pre = ""
url = "/services"
weight = 2

[[menu.main]]
name = "Team"
pre = "/"
url = "about/#team"
weight = 2




[[menu.main]]
name = "News"
pre = ""
url = "news"
weight = 5

[[menu.main]]
name = "learning Center"
pre = ""
url = "/learning"
weight = 6

[[menu.main]]
name = "News"
pre = ""
url = "/news"
weight = 7



[[menu.main]]
name = "Tax"
pre = ""
url = "/tax"
weight = 8

[[menu.main]]
name = "contact"
pre = "#"
url = "contact"
weight = 9



############################# Default Parameters ##########################
[params]
logo = "MES Logo.png"
# Meta data
description = "Myanmar Enterprise Solutions is about bringing our clients a positive outsourcing experience for their accounting and corporate financial planning needs."
author = "MES"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = true
preloader = "MES Logo.png"

# cookies
[params.cookies]
enable = true
expire_days = 2





############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
link = "#"



################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2020 Myanmar Enterprise Solutions | Powered by"


